# start = false
# document.body.addEventListener 'mousedown', (event) ->
#   if event.clientX < 10
#     start = true
#   return
# document.body.addEventListener 'mousemove', (event) ->
#   if start and event.clientX > 20
#     console.log 'menu?'
#     start = false
#   return
# document.body.addEventListener 'mouseup', (event) ->
#   if start and event.clientX > 20
#     console.log 'menu?'
#   start = false
#   return
message = "ist drin"
ipc = require('ipc')
# ipc.sendToHost('pong')

console.log "test"

ipc.on 'get-sidebar', () ->
  d = document.getElementById 'sidebar'
  # ipc.sendToHost 'sidebar', d.outerHTML
  header = document.getElementsByTagName 'header'
  header[0].classList.add 'hide'
  content = document.getElementById 'main-content'
  content.classList.add 'hide'


# copyMenu = ->
#   console.log daisy.contents().find("#sidebar").append $('<div>BLAAA</div>')
#
# copyMenu()

# ---
# generated by js2coffee 2.1.0
